export const internshipCompanies = [
    {
        "company": "Turing",
        "ctc": 30000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Reckitt",
        "ctc": 10000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CH"]
    },
    {
        "company": "Reliance Industries Limited",
        "ctc": 30000,
        "type": "intern",
        "cutoff": 6,
        "program": "BTech",
        "branches": ["CH", "ME"]
    },
    {
        "company": "Morgan Stanley",
        "ctc": 87000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EN",
            "EP",
            "IT",
            "EE",
            "MCE",
            "ME",
            "EC",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Expedia",
        "ctc": 35000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "IT", "MCE", "SE"]
    },
    {
        "company": "Expedia",
        "ctc": 35000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "IT", "SE", "MCE"]
    },
    {
        "company": "Moody's",
        "ctc": 26000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "My Analytics School",
        "ctc": 10000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "WAISL",
        "ctc": 15000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Walmart",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Macquarie Global Services (I) Pvt ltd.",
        "ctc": 50000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "ME", "SE"]
    },
    {
        "company": "Simpl (One Sigma Pvt Technologies)",
        "ctc": 60000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "DARPG ,Data & Strategy Unit",
        "ctc": 50000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "IT", "MCE", "SE"]
    },
    {
        "company": "Hero Motocorp Ltd",
        "ctc": 20000,
        "type": "intern",
        "cutoff": 8,
        "program": "BTech",
        "branches": ["ME"]
    },
    {
        "company": "Fiserv",
        "ctc": 30000,
        "type": "intern",
        "cutoff": 8,
        "program": "BTech",
        "branches": ["CO", "IT", "MCE", "SE"]
    },
    {
        "company": "Becton Dickinson ",
        "ctc": 20000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["ME", "AE"]
    },
    {
        "company": "Becton Dickinson ",
        "ctc": 20000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["SE", "IT", "CO", "MCE"]
    },
    {
        "company": "Fundwave",
        "ctc": 65000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Amazon",
        "ctc": 110000,
        "type": "intern",
        "cutoff": 6.5,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "SE"]
    },
    {
        "company": "Flovel Energy Private Limited",
        "ctc": 15000,
        "type": "intern",
        "cutoff": 9,
        "program": "BTech",
        "branches": ["AE", "ME", "PE"]
    },
    {
        "company": "McKinley Rice",
        "ctc": 25000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Microsoft",
        "ctc": 25000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Indus Valley Partners",
        "ctc": 45000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Placewit",
        "ctc": 10000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Placewit",
        "ctc": 12000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Placewit",
        "ctc": 40000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Placewit",
        "ctc": 75000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Nasdaq",
        "ctc": 50000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EE",
            "EN",
            "EP",
            "IT",
            "EC",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Truminds Software Systems",
        "ctc": 20000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "EP", "IT", "MCE", "EE", "SE"]
    },
    {
        "company": "Accenture",
        "ctc": 50000,
        "type": "intern",
        "cutoff": 6.5,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Samsung R&D Institute Banglore",
        "ctc": 50000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "SE", "MCE"]
    },
    {
        "company": "Plotline",
        "ctc": 55000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "BT",
            "AE",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Plotline",
        "ctc": 55000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EN",
            "EP",
            "IT",
            "MCE",
            "EE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Plotline",
        "ctc": 55000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EN",
            "EP",
            "IT",
            "MCE",
            "EE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "PayPal",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "PayPal",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Indian Air Force",
        "ctc": 0,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "IT", "MCE", "SE"]
    },
    {
        "company": "LinkedIn",
        "ctc": 40000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "AE",
            "EN",
            "IT",
            "MCE",
            "ME",
            "EP",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Bechtel",
        "ctc": 25000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["AE", "CH", "CE", "EC", "EE", "EN", "EP", "ME", "PE"]
    },
    {
        "company": "GetStructured.tech",
        "ctc": 85000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "GetStructured.tech",
        "ctc": 80000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "CH",
            "BT",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Visa",
        "ctc": 65000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "IT", "MCE", "EP", "SE"]
    },
    {
        "company": "Citi Bank",
        "ctc": 75000,
        "type": "intern",
        "cutoff": 6.5,
        "program": "BTech",
        "branches": ["CO", "IT", "SE", "MCE", "EC", "EE", "EP"]
    },
    {
        "company": "Morgan Stanley",
        "ctc": 87000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": ["IT", "MCE", "SE", "CO", "EC", "EP", "EE"]
    },
    {
        "company": "Bank of New York Mellon",
        "ctc": 75000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "SE"]
    },
    {
        "company": "Wells Fargo",
        "ctc": 90000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "SE"]
    },
    {
        "company": "Deutsche Bank",
        "ctc": 75000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "IT", "MCE", "SE"]
    },
    {
        "company": "Fastenal",
        "ctc": 70000,
        "type": "intern",
        "cutoff": 8.5,
        "program": "BTech",
        "branches": ["CO", "IT"]
    },
    {
        "company": "Thorogood",
        "ctc": 35000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Atlassian",
        "ctc": 130000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "IT", "MCE", "SE"]
    },
    {
        "company": "Axxela",
        "ctc": 45000,
        "type": "intern",
        "cutoff": 5,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Schlumberger",
        "ctc": 60000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "SE"]
    },
    {
        "company": "Flipkart",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": ["CO", "EC", "EE", "EP", "IT", "MCE", "SE"]
    },
    {
        "company": "Adobe",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "IT", "SE", "MCE", "EC", "EE", "EP"]
    },
    {
        "company": "Arcesium",
        "ctc": 125000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["SE", "MCE", "IT", "EP", "EE", "EC", "CO"]
    },
    {
        "company": "WinZO Games",
        "ctc": 125000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": ["CO", "MCE", "SE", "IT"]
    },
    {
        "company": "DevRev",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 8.5,
        "program": "BTech",
        "branches": ["CO", "IT", "SE"]
    },
    {
        "company": "Texas Instruments",
        "ctc": 60000,
        "type": "intern",
        "cutoff": 6,
        "program": "BTech",
        "branches": ["EC", "EE", "EP"]
    },
    {
        "company": "Texas Instruments",
        "ctc": 60000,
        "type": "intern",
        "cutoff": 6,
        "program": "BTech",
        "branches": ["EE", "EC", "EP"]
    },
    {
        "company": "Texas Instruments",
        "ctc": 60000,
        "type": "intern",
        "cutoff": 6,
        "program": "BTech",
        "branches": ["CO", "EE", "EC", "EP"]
    },
    {
        "company": "FischerJordan",
        "ctc": 40000,
        "type": "intern",
        "cutoff": 7.5,
        "program": "BTech",
        "branches": [
            "CO",
            "CH",
            "EE",
            "CE",
            "EC",
            "EN",
            "EP",
            "BT",
            "AE",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Adobe",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["CO", "IT", "SE", "MCE", "EC", "EE", "EP"]
    },
    {
        "company": "Trilogy Innovations (Codenation)",
        "ctc": 75000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Intuit",
        "ctc": 100000,
        "type": "intern",
        "cutoff": 8,
        "program": "BTech",
        "branches": ["EE", "MCE", "IT", "EC", "SE", "CO"]
    },
    {
        "company": "Uber",
        "ctc": 177000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Sprinklr",
        "ctc": 200000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "BT",
            "CH",
            "CE",
            "CO",
            "EC",
            "EE",
            "AE",
            "EN",
            "IT",
            "MCE",
            "ME",
            "EP",
            "PE",
            "SE"
        ]
    },
    {
        "company": "Microsoft",
        "ctc": 125000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": [
            "CH",
            "CE",
            "CO",
            "EC",
            "BT",
            "EE",
            "EN",
            "EP",
            "IT",
            "AE",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    },
    {
        "company": "DE Shaw",
        "ctc": 150000,
        "type": "intern",
        "cutoff": 7,
        "program": "BTech",
        "branches": ["SE", "CO", "MCE", "IT", "EE", "EC", "EP"]
    },
    {
        "company": "Search Your Merch",
        "ctc": 5000,
        "type": "intern",
        "cutoff": 0,
        "program": "BTech",
        "branches": [
            "AE",
            "CH",
            "CE",
            "CO",
            "EC",
            "BT",
            "EE",
            "EN",
            "EP",
            "IT",
            "MCE",
            "ME",
            "PE",
            "SE"
        ]
    }
]
