
import React from 'react';

const PrivacyPolicy = () => {
    return (
        <div className=' md:my-20 my-10  flex flex-col justify-between '>

            <div className="p-6 max-w-3xl mx-auto">

                <h2 className="text-2xl font-semibold mb-4">Privacy Policy</h2>
                <p className="mb-4">Last updated: 07 July 2024</p>
                <p className="mb-4">
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>

                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Interpretation and Definitions</h2>
                <h3 className="subHeadPvc text-lg font-semibold mb-2">Interpretation</h3>
                <p className="mb-4">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                <h3 className="text-lg font-semibold mb-2">Definitions</h3>
                <p className="mb-4">For the purposes of this Privacy Policy:</p>
                <ul className=" list-inside mb-4">
                    <li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
                    <li><p><strong>Company</strong> (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to DTU Rankwallah, Delhi Technological University, Shahbad Daulatpur Village, Rohini.</p></li>
                    <li><p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
                    <li><p><strong>Country</strong> refers to: Delhi, INDIA</p></li>
                    <li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p></li>
                    <li><p><strong>Service</strong> refers to the Website.</p></li>
                    <li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
                    <li><p><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p></li>
                    <li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
                    <li><p><strong>Website</strong> refers to DTU Rankwallah, accessible from <a href="https://rankwallah.in/" rel="external nofollow noopener noreferrer" target="_blank">https://rankwallah.in/</a></p></li>
                    <li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
                </ul>
                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Collecting and Using  Data</h2>
                <h3 className="subHeadPvc text-lg font-semibold mb-2">Types of Data Collected</h3>

                <h3 className="text-lg font-semibold mb-2">Usage Data</h3>
                <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
                <p className="mb-4">
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p className="mb-4">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p className="mb-4">
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>
                <h3 className="text-lg font-semibold mb-2">Tracking Technologies and Cookies</h3>
                <p className="mb-4">
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                </p>
                <ul className=" list-inside mb-4">
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read 'Where can I change the settings for disabling, or deleting local shared objects?' available at <a href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_" rel="external nofollow noopener noreferrer" target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a></li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                </ul>
                <p className="mb-4">Cookies can be 'Persistent' or 'Session' Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <ul className=" list-inside mb-4">
                    <li><p><strong>Necessary / Essential Cookies</strong></p>
                        <p>Type: Session Cookies</p>
                        <p>Administered by: Us</p>
                        <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                    </li>
                    <li><p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                        <p>Type: Persistent Cookies</p>
                        <p>Administered by: Us</p>
                        <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    </li>
                    <li><p><strong>Functionality Cookies</strong></p>
                        <p>Type: Persistent Cookies</p>
                        <p>Administered by: Us</p>
                        <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                    </li>
                </ul>

                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Analytics</h2>
                <p className="mb-4">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
                <ul className=" list-inside mb-4">
                    <li><p><strong>Google Analytics</strong></p>
                        <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
                        <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
                        <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" rel="external nofollow noopener noreferrer" target="_blank">https://policies.google.com/privacy?hl=en</a></p>
                    </li>
                </ul>
                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Links to Other Websites</h2>
                <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <p className="mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Changes to this Privacy Policy</h2>
                <p className="mb-4">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <p className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                <h2 className="subHeadPvcH2 text-xl font-semibold mb-2">Contact Us</h2>
                <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className=" list-inside mb-4">
                    <li><p>By email: onlyjunaid2002@gmail.com</p></li>
                    <li><p>By visiting this page on our website: <a href="https://rankwallah.in/contact" rel="external nofollow noopener noreferrer" target="_blank">https://rankwallah.in/contact</a></p></li>
                </ul>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
